name: .NET Core

on:
  - push

env:
  NUGET_UPLOAD_URL: https://nuget.pkg.github.com/carbonfrost/
  NUGET_SOURCE_URL: https://nuget.pkg.github.com/carbonfrost/index.json
  NUGET_SOURCE_NAME: Carbonfrost
  NUGET_USER_NAME: ${{ github.actor }}
  NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERBOSE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
       nuget-version: latest

    - name: Check environment
      run: make --version; make env

    - name: Configure dotnet and NuGet
      run: make dotnet/configure

    - name: Restore with dotnet
      run: make dotnet/restore

    - name: Build with dotnet
      run: make -- -dotnet/build
